ARTIST_ABBREVIATIONS = {
    'mj': 'Michael Jackson',
    'jt': 'Justin Timberlake',
    'bts': 'BTS',
    'acdc': 'AC/DC',
    'em': 'Eminem',
    'ts': 'Taylor Swift',
    'jb': 'Justin Bieber',
    'bey': 'Beyoncé',
    'rih': 'Rihanna',
    'weeknd': 'The Weeknd',
    'drizzy': 'Drake',
    'kdot': 'Kendrick Lamar',
    'qe': 'Queen',
    'ledzep': 'Led Zeppelin',
    'bruno': 'Bruno Mars',
    'xtina': 'Christina Aguilera',
    'gaga': 'Lady Gaga',
    'elton': 'Elton John',
    'adele': 'Adele',
    'beatles': 'The Beatles',
    'pinkfloyd': 'Pink Floyd',
    'coldplay': 'Coldplay',
    'u2': 'U2',
    'metal': 'Metallica',
    'ozzy': 'Ozzy Osbourne',
    'snoop': 'Snoop Dogg',
    'biggie': 'The Notorious B.I.G.',
    'pac': '2Pac',
    'nirvana': 'Nirvana',
    'queenb': 'Beyoncé',
    'jay': 'Jay-Z',
    'riRi': 'Rihanna',
    'shady': 'Eminem',
    'taytay': 'Taylor Swift',
    'harry': 'Harry Styles',
    'posty': 'Post Malone',
    'biebs': 'Justin Bieber',
}
