# Generated by Django 5.2 on 2025-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='artists_art_name_68abb5_idx'), models.Index(fields=['genre'], name='artists_art_genre_5a480a_idx'), models.Index(fields=['location'], name='artists_art_locatio_a22a5a_idx')],
            },
        ),
    ]
