# Generated by Django 5.2 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='artists_new_name_dcddb9_idx'), models.Index(fields=['genre'], name='artists_new_genre_3ef7a4_idx'), models.Index(fields=['location'], name='artists_new_locatio_6b16b6_idx')],
            },
        ),
    ]
